### ISSUE TITLE
Porządki, uproszczenie nazewnictwa katalogów i plików

### ISSUE THREAD

**Issue by MiroslawZoladz** [kbolek/praca_inzynierska_bolek#1]
1. Temperatura
    * PC
        * acqusition.py
    * uC (usunąć listę komend, jeśli opis programu to w środku)
        * main.ino
2. Zasilanie
3. Synchronizacja

**Comment by kbolek** [comment]
Test. Katalogi uporządkowane (puste katalogi nie są widoczne domyślnie).
